In [0]:
import numpy as np
import pandas as pd

In [0]:
x = np.array([[1,1,1,1,1,1],[-1,-1,-1,-1,-1,-1],[1 ,-1, -1,1, 1, 1 ],[1,1,-1,-1,-1,-1]])
y = np.array([[1,1,1],[-1,-1,-1],[-1,1,1],[1,-1,1]])

As input is bipolar 

In [0]:
w = np.matmul(x.T, y)
v = w.T
epoches = 1000
Del = 0.2
eta = 1/((2*(1-2*Del)*max(w.shape)) + 1)
for i in range(epoches):
  #calculating activations
  y_t = np.matmul(x, w)
  x_t = np.matmul(y, v)
  #transmission forward
  for j in range(len(y_t)):
    for k in range(len(y_t.T)):
      if(y_t[j, k] > 1):
        y_t[j, k] = 1
      elif(y_t[j, k] < -1) :
        y_t[j, k] = -1
      else:
        y_t[j, k] = (Del + 1) * y_t[j, k] - Del * y_t[j, k]**3

  #transmission backward
  for j in range(len(x_t)):
    for k in range(len(x_t.T)):
      if(x_t[j, k] > 0):
        x_t[j, k] = 1
      elif(x_t[j, k] < -1) :
        x_t[j, k] = -1
      else:
        x_t[j, k] = (Del + 1) * x_t[j, k] - Del * x_t[j, k]**3
  w = w + eta * np.matmul((x + x_t).T, (y - y_t))
  v = v + eta * np.matmul((y + y_t).T, (x - x_t))
  # in paper it says or condition is sufficient
  if((y == y_t).all() and (x == x_t).all()):
    break





Input flipped by one bit

In [0]:
x_test = np.array([[1,1,1,1,1,-1],[-1,-1,-1,-1,1,-1],[1 ,-1, -1,1, -1, 1 ],[1,1,-1,-1,-1,1]])
y_t = np.matmul(x_test, w)
for j in range(len(y_t)):
  for k in range(len(y_t.T)):
    if(y_t[j, k] > 1):
      y_t[j, k] = 1
    elif(y_t[j, k] < -1) :
      y_t[j, k] = -1
    else:
      y_t[j, k] = (Del + 1) * y_t[j, k] - Del * y_t[j, k]**3


In [19]:
for i in range(len(x_test)):
  print(x_test[i,:], y_t[i,:])

[ 1  1  1  1  1 -1] [1. 1. 1.]
[-1 -1 -1 -1  1 -1] [-1. -1. -1.]
[ 1 -1 -1  1 -1  1] [-1.  1.  1.]
[ 1  1 -1 -1 -1  1] [ 1. -1.  1.]
